##Default Git URL
server:
  port: 8088

## Private Access Token enabled to ignore password for gitlabs
spring:
  cloud:
    config:
      server:
        git:
          uri: 
          username: 
          password: 
          clone-on-start: true
          search-paths: "*"


  application:
    name: BHARAD-CLOUD-CONFIG


info:
  app:
    name: Bharad Cloud Config
    description: Bharad cloud config to read properties from outside
    version: 0.0.1

#Eureka Client Properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.18.204.135:8761/eureka/
      

---
